'''numero1 = 5
numero2 = 2

soma = numero1 + numero2
subtracao = numero1 - numero2
multiplicacao = numero1 * numero2
divisao = numero1 / numero2
divisaoInteira = numero1 // numero2
modulo = numero1 % numero2
exponenciacao = numero1 ** numero2

print(soma)
print(subtracao)
print(multiplicacao)
print(divisao)
print(divisaoInteira)
print(modulo)
print(exponenciacao)'''

'''numero1 = 5
numero1 += 5
numero1 -= 3
print(numero1)'''

'''a = 6
b = 8
c = 3

soma = a + b 
if soma > 10:
    print("Soma maior ou igual a 10")
else:
    print("Soma não é maior que 10")'''
    
'''print("Qual seu nome?: ")  
nome = input()
print("Qual sua idade? ")
idade = input()
print("Seu nome é: ", nome)
print("Sua idade é: ", idade)'''

'''soma1 = 7 + 8
soma2 = 10 + 5

if soma1 == soma2:
    print("Os resultados são iguais")
else:
    print("Os resultados são diferentes")'''
    
a = 5
b = 10
'''print((a > 0) and (b !=0))
print((a > 0) and (b==0))'''
'''print ((a>0) or (b == 0) )
print((a>0) or (a != 0))'''

'''print(not(a > 0))
print(not(a == 0))'''

'''a = int(input("Digite um número: "))
impar = ((a % 2) ==1)
if impar:
    print("Número ímpar")
else :
    print("Número par")
print("Fim do programa")'''

'''a = int(input("Digite um número: "))
if (a % 2) ==1:
    print("Número ímpar")
else :
    print("Número par")
print("Fim do programa")'''

'''a = int(input("Digite um número: "))
if (a % 2) ==1:
    print("Número ímpar")
if (a % 2) ==0:
    print("Número par")'''
'''for letra in "Elizabeth":
    print(letra)'''

'''a = float(input("Digite o primeiro número: "))
b = float(input("Digite o segundo número: "))

if a > b: 
    print("O maior número é", a)
else:
    print("O menor número é ", b)'''

'''a = float(input("Digite o primeiro número: "))
b = float(input("Digite o segundo número: "))'''

'''if a == b: 
    print("Os dois números são iguais")
else:
    if a > b :
        print("O maior número é o primeiro")
    else:
        print("O maior número é o segundo")'''

'''clima = input("Como está o clima hoje?: ")
if clima == "Ensolarado" or "Sol" or "Quente":
    print("praia")
else:
    print("netflix")'''

'''clima = input("Como está o clima hoje? ")
if clima == "Sol" and "Quente" and "Ensolarado":
    print("Massa!")
else:
    print("Netflix")
condicao = input("Você tem dinheiro? ")
if condicao == "Sim":
    print("Vai dar praia, papai")
else:
    print("Netflix")'''
    
'''tempo = input("Está fazendo sol? ")
dinheiro = input("Você tem dinheiro? ")
if (tempo == "sim" and dinheiro == "sim"):
    print("Vamos à praia")
else:
    print("Vamos assistir netflix. ")'''